---
title: "R Notebook"
output: html_notebook
---



```{r}

if (!require("dplyr")) {
  install.packages("dplyr", repos="http://cran.rstudio.com/") 
}
if (!require("data.table")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("reshape")) {
  install.packages("reshape", repos="http://cran.rstudio.com/") 
}
if (!require("lsa")) {
  install.packages("lsa", repos="http://cran.rstudio.com/") 
}

library(dplyr)
library(data.table)
library(reshape)
library(lsa)
library(pbapply)

```

```{r}

########################## CONSTANTS ##########################

address <- "/local/Scripts/moad/"

```

```{r}

########################## DATA LOAD ############################

data.train <- fread(paste0(address,"data/LFM_train.txt"), 
                    sep = "\t", 
                    verbose = TRUE,
                    header = TRUE)
data.train = as.data.frame(data.train)

users = data.train$`user-id` %>% unique()

all.ilds = fread(paste0(address,"results/daily.propensity.ILD.allusers.txt"), 
                 sep = ",") 

# clean zeros and median
names(all.ilds) = c("day", "contemporaneity", "locality", "genre")
all.ilds.filtered = filter(all.ilds, contemporaneity > 0 & locality > 0 & genre > 0)

summary.contemporaneity = summary(all.ilds.filtered$contemporaneity)
summary.locality = summary(all.ilds.filtered$locality)
summary.genre = summary(all.ilds.filtered$genre)

```

```{r}

ild.2.scenario.hard = function(ilds) {
  x = 0; y = 0; z = 0
  if(ilds[1] >= summary.contemporaneity[3]) {x = 1}
  if(ilds[2] >= summary.locality[3]) {y = 1}
  if(ilds[3] >= summary.genre[3]) {z = 1}
  return(c(x, y, z) %>% as.data.frame())
}

ild.2.scenario = function(ilds) {
  x = 0.5; y = 0.5; z = 0.5
  if(ilds[1] >= summary.contemporaneity[5]) {x = 1}
  if(ilds[1] <= summary.contemporaneity[2]) {x = 0}
  if(ilds[2] >= summary.locality[5]) {y = 1}
  if(ilds[2] <= summary.locality[2]) {y = 0}
  if(ilds[3] >= summary.genre[5]) {z = 1}
  if(ilds[3] <= summary.genre[2]) {z = 0}
  return(c(x, y, z))
}

# test
# user = 7687

generate.scenario.by.ild = function(user){
  user.ilds = fread(paste0(address, "results/daily.propensity.ILD.user", user, ".txt"))
  names(user.ilds) = c("day", "contemporaneity", "locality", "genre")
  days = user.ilds$day
  user.ilds = user.ilds[,-1]
  res = apply(user.ilds, 1, ild.2.scenario) %>% t() %>% as.data.frame()
  res = cbind(days, res)
  fwrite(res, paste0(address, "results/daily.propensity.scenario.user", user, ".txt"), sep = "\t", row.names = F, col.names = F)
}

pblapply(users, generate.scenario.by.ild)

```
