---
title: "R Notebook"
output: html_notebook
---


```{r}

if (!require("dplyr")) {
  install.packages("dplyr", repos="http://cran.rstudio.com/") 
}
if (!require("data.table")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("pbapply")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("ggplot2")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("reshape")) {
  install.packages("reshape", repos="http://cran.rstudio.com/") 
}

library(dplyr)
library(data.table)
library(pbapply)
library(ggplot2)
library(reshape)

```

```{r}

address <- "/local/Scripts/moad/"

```

```{r}

########################## DATA LOAD ############################

data.train <- fread(paste0(address,"data/LFM_train.txt"), 
                    sep = "\t", 
                    verbose = TRUE,
                    header = TRUE)
data.train = as.data.frame(data.train)

users = data.train$`user-id` %>% unique()

```

```{r}
coincidence = function(real, chosen){
  if(length(chosen) == length(real)){
    sum.vec = chosen %>% as.numeric() + real %>% as.numeric()
    #sum.vec = ((sum.vec %% 2) - 1) %>% abs()
    sum.vec = (sum.vec == 1) %>% as.numeric()
    return((length(sum.vec) - sum(sum.vec)) / length(sum.vec))
  }
}
```

```{r}

# Baseline - previous day ILD 

# test
# user = users[1]
# days = 7

baseline.regrets = function(user, days){
  
  scenarios = fread(paste0(address, "results/daily.propensity.scenario.user", user,".txt"),
        sep = "\t", header = F)
  scenarios.ildpd = fread(paste0(address, "resultsildpd/shiftband.ild.daily.user", user,".txt"),
        sep = ",", header = F)
  scenarios.ildpd = scenarios.ildpd %>% select(V5,V6,V7) %>% slice(-n())
  
  linha = data.frame(V5 = sample(c(0,1), size = 1), V6 = sample(c(0,1), size = 1), V7 = sample(c(0,1), size = 1))
  scenarios.ildpd = bind_rows(linha, scenarios.ildpd)
  scenarios.ildpd = cbind(scenarios[,1], scenarios.ildpd, scenarios[,c(2:4)])
  names(scenarios.ildpd) = c("day", "P1", "P2", "P3", "R1", "R2", "R3")
  
  day.regret = function(vec){
    return(1 - coincidence(vec[2:4], vec[5:7]))
  }
  
  # break into pieces
  train.part = 4
  freeze.days = ceiling(nrow(scenarios.ildpd) / train.part)
  left = scenarios.ildpd %>% select(1)
  right = scenarios.ildpd %>% select(5:7)
  scenarios.ildpd.cut = scenarios.ildpd %>% select(c(2:4))
  top = scenarios.ildpd.cut %>% slice(1:freeze.days)
  scenarios.ildpd.cut = scenarios.ildpd.cut %>% slice((freeze.days+1):n())
  
  # generate freezed scenarios
  df = data.frame()
  for(i in 1:(ceiling(nrow(scenarios.ildpd.cut) / days)) - 1){
    df = rbind(df, 
               cbind(rep(scenarios.ildpd.cut[i * days + 1, 1], days) %>% as.data.frame() %>% t(), 
                     rep(scenarios.ildpd.cut[i * days + 1, 2], days) %>% as.data.frame() %>% t(), 
                     rep(scenarios.ildpd.cut[i * days + 1, 3], days) %>% as.data.frame() %>% t()))
  }
  df = df %>% slice(1:nrow(scenarios.ildpd.cut))
  names(df) = c("P1", "P2", "P3")
  
  # assemble back
  
  df = rbind(top, df)
  scenarios.ildpd = cbind(left, df, right)
  
  regrets = cbind(user, apply(scenarios.ildpd, 1, day.regret)) %>% as.data.frame()
  names(regrets) = c("day", "regret")
  
  mean.regret = c()
  for(day in 1:nrow(regrets)){
        mean.regret = c(mean.regret, sum(regrets$regret[1:day] * c(1:day)) / sum(1:day)) # weighted average in relation to position in timeline
  }
  mean.regret = cbind(regrets$day, mean.regret %>% as.data.frame())
  names(mean.regret) = c("day", "regret")
  
  fwrite(mean.regret,
         paste0(address,"resultsildpd/hard.ildpd.freeze25%.", days, "days.daily.regret.user", user, ".txt"),
         row.names = FALSE, col.names = FALSE, sep = "\t")
  
}

pblapply(users, baseline.regrets, 14)

```


```{r}

# Calculate regrets

# test
# user = users[1]

calculate.regrets = function(user, days){
  
  scenarios = fread(paste0(address, "resultsentropy/daily.scenario.user", user,".txt"),
        sep = "\t", header = F)
  
  # hard scenarios
  scenarios.hard = fread(paste0(address, "results/daily.propensity.scenario.user", user,".txt"),
        sep = "\t", header = F)
  scenarios = cbind(scenarios, scenarios.hard)
  scenarios = scenarios[,c(-5, -6, -7, -8)]
  names(scenarios) = c("day", "P1", "P2", "P3", "R1", "R2", "R3")
  
  day.regret = function(vec){
    return(1 - coincidence(vec[2:4], vec[5:7]))
  }
  
  # break into pieces
  train.part = 4
  freeze.days = ceiling(nrow(scenarios) / train.part)
  left = scenarios %>% select(1)
  right = scenarios %>% select(5:7)
  scenarios.cut = scenarios %>% select(c(2:4))
  top = scenarios.cut %>% slice(1:freeze.days)
  scenarios.cut = scenarios.cut %>% slice((freeze.days+1):n())
  
  # generate freezed scenarios
  df = data.frame()
  for(i in 1:(ceiling(nrow(scenarios.cut) / days)) - 1){
    df = rbind(df, 
               cbind(rep(scenarios.cut[i * days + 1, 1], days) %>% as.data.frame() %>% t(), 
                     rep(scenarios.cut[i * days + 1, 2], days) %>% as.data.frame() %>% t(), 
                     rep(scenarios.cut[i * days + 1, 3], days) %>% as.data.frame() %>% t()))
  }
  df = df %>% slice(1:nrow(scenarios.cut))
  names(df) = c("P1", "P2", "P3")
  
  # assemble back
  
  df = rbind(top, df)
  scenarios = cbind(left, df, right)
  
  regrets = cbind(scenarios$day, apply(scenarios, 1, day.regret)) %>% as.data.frame()
  names(regrets) = c("day", "regret")
  
  mean.regret = c()
  for(day in 1:nrow(regrets)){
        mean.regret = c(mean.regret, sum(regrets$regret[1:day] * c(1:day)) / sum(1:day)) # weighted average in relation to position in timeline
  }
  mean.regret = cbind(regrets$day, mean.regret %>% as.data.frame())
  names(mean.regret) = c("day", "regret")
  
  fwrite(mean.regret,
         paste0(address,"resultsshiftbandfreeze/hard.shiftband.freeze.", days, "days.daily.regret.user", user, ".txt"),
         row.names = FALSE, col.names = FALSE, sep = "\t")
  
}

pblapply(users, calculate.regrets, 14)

```

```{r}

# test
# user = users[176]

# regret.line = regrets$ShiftBand
integrate.regrets = function(regret.line){
  day.range = ((1:(length(regret.line))) - 1) /  ((length(regret.line) - 1))
  integrate(approxfun(day.range , regret.line), 0, 1, subdivisions = 10000, stop.on.error = FALSE)$value
}

generate.line.areas = function(user){
  
  sb.freeze.7days = fread(paste0(address, "resultsshiftbandfreeze/hard.shiftband.freeze.7days.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
  
  if(sb %>% nrow() > 1){
    
    sb.freeze.14days = fread(paste0(address, "resultsshiftbandalpha01beta05gamma05/hard.shiftband.alpha01.beta05.gamma05.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
    ildpd.freeze.7days = fread(paste0(address, "resultsildpd/hard.ildpd.freeze25%.7days.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd.freeze.14days = fread(paste0(address, "resultsildpd/hard.ildpd.freeze25%.14days.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    
    
    regrets = cbind(sb.freeze.7days, sb.freeze.14days, ildpd.freeze.7days, ildpd.freeze.14days)  
    regrets = regrets[,c(-1, -3, -5, -7)]
    names(regrets) = c("ShiftBand7", "ShiftBand14", "ILDPD7", "ILDPD14")
    
    apply(regrets, 2, integrate.regrets)
    
  }
}

regret.area = pbsapply(users, generate.line.areas) %>% t()

fwrite(regret.area %>% as.data.frame(), 
       paste0(address, "resultsarea/hard.regret.area.sbfreeze.ildpdfreeze.txt"),
       sep = "\t",
       row.names = F,
       col.names = T)

```



```{r}

regret.area.melted = melt(regret.area %>% as.data.frame(), measure.vars = c(1:(regret.area %>% ncol())))
names(regret.area.melted) = c("method", "value")

g = ggplot(regret.area.melted, aes(x = method, y = value, fill = method)) +
  geom_boxplot() +
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g

ggsave(paste0(address, "resultsarea/plot.shiftband.ildpd.severaldays.pdf"))
```

