---
title: "R Notebook"
output: html_notebook
---


```{r}

if (!require("dplyr")) {
  install.packages("dplyr", repos="http://cran.rstudio.com/") 
}
if (!require("data.table")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("pbapply")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("ggplot2")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("reshape")) {
  install.packages("reshape", repos="http://cran.rstudio.com/") 
}

library(dplyr)
library(data.table)
library(pbapply)
library(ggplot2)
library(reshape)

```

```{r}

address <- "/local/Scripts/moad/"

```

```{r}

########################## DATA LOAD ############################

data.train <- fread(paste0(address,"data/LFM_train.txt"), 
                    sep = "\t", 
                    verbose = TRUE,
                    header = TRUE)
data.train = as.data.frame(data.train)

users = data.train$`user-id` %>% unique()

```

```{r}
coincidence = function(real, chosen){
  if(length(chosen) == length(real)){
    sum.vec = chosen %>% as.numeric() + real %>% as.numeric()
    #sum.vec = ((sum.vec %% 2) - 1) %>% abs()
    sum.vec = (sum.vec == 1) %>% as.numeric()
    return((length(sum.vec) - sum(sum.vec)) / length(sum.vec))
  }
}
```

```{r}

# Baseline - previous day ILD 

# test
# user = users[1]

baseline.regrets = function(user){
  
  scenarios = fread(paste0(address, "results/daily.propensity.scenario.user", user,".txt"),
        sep = "\t", header = F)
  scenarios.ildpd = fread(paste0(address, "resultsildpd/shiftband.ild.daily.user", user,".txt"),
        sep = ",", header = F)
  scenarios.ildpd = scenarios.ildpd %>% select(V5,V6,V7) %>% slice(-n())
  
  linha = data.frame(V5 = sample(c(0,1), size = 1), V6 = sample(c(0,1), size = 1), V7 = sample(c(0,1), size = 1))
  scenarios.ildpd = bind_rows(linha, scenarios.ildpd)
  scenarios.ildpd = cbind(scenarios[,1], scenarios.ildpd, scenarios[,c(2:4)])
  
  day.regret = function(vec){
    return(1 - coincidence(vec[2:4], vec[5:7]))
  }
  
  regrets = cbind(user, apply(scenarios.ildpd, 1, day.regret)) %>% as.data.frame()
  names(regrets) = c("day", "regret")
  
  # mean.regret = c()
  # for(day in 1:nrow(regrets)){
  #       mean.regret = c(mean.regret, sum(regrets$regret[1:day] * c(1:day)) / sum(1:day)) # weighted average in relation to position in timeline
  # }
  # mean.regret = cbind(regrets$day, mean.regret %>% as.data.frame())
  # names(mean.regret) = c("day", "regret")
  # 
  # fwrite(mean.regret,
  #        paste0(address,"resultsildpd/hard.ildpd.daily.regret.user", user, ".txt"),
  #        row.names = FALSE, col.names = FALSE, sep = "\t")
  
  fwrite(regrets,
         paste0(address,"resultsildpd/ildpd.daily.regret.nomean.user", user, ".txt"),
         row.names = FALSE, col.names = FALSE, sep = "\t")

}

pblapply(users, baseline.regrets)

```

```{r}

# Baseline - several days ILD 

# test
# user = users[1]
# days = 7

baseline.regrets = function(user, days){
  
  scenarios = fread(paste0(address, "results/daily.propensity.scenario.user", user,".txt"),
        sep = "\t", header = F)
  if(nrow(scenarios) > days){
    
    ilds = scenarios %>% select(V2, V3, V4)
    ilds.fdays = ilds %>% slice((days+1) : n())
    ilds.ldays = ilds %>% slice(1:(n()-days))
    ilds.days = scenarios %>% select(V1) %>% slice((days+1) : n())
    
    scenarios.ild = cbind(ilds.days, ilds.fdays, ilds.ldays)
    
    day.regret = function(vec){
      return(1 - coincidence(vec[2:4], vec[5:7]))
    }
    
    regrets = cbind(user, apply(scenarios.ild, 1, day.regret)) %>% as.data.frame()
    names(regrets) = c("day", "regret")
    
    mean.regret = c()
    for(day in 1:nrow(regrets)){
          mean.regret = c(mean.regret, sum(regrets$regret[1:day] * c(1:day)) / sum(1:day)) # weighted average in relation to position in timeline
    }
    mean.regret = cbind(regrets$day, mean.regret %>% as.data.frame())
    names(mean.regret) = c("day", "regret")
    
    fwrite(mean.regret,
           paste0(address,"resultsildpd/hard.ildpd.", days,"days.daily.regret.user", user, ".txt"),
           row.names = FALSE, col.names = FALSE, sep = "\t")
  }
}

pblapply(users, baseline.regrets, 7)
pblapply(users, baseline.regrets, 2)
pblapply(users, baseline.regrets, 5)
pblapply(users, baseline.regrets, 15)


```

```{r}

# Calculate regrets

# test
# user = users[1]

calculate.regrets = function(user){
  
  scenarios = fread(paste0(address, "resultsshiftband2/shiftband.ild.daily.user", user,".txt"),
        sep = ",", header = F)
  
  # hard scenarios
  # scenarios.hard = fread(paste0(address, "results/daily.propensity.scenario.user", user,".txt"),
  #       sep = "\t", header = F)
  # scenarios = cbind(scenarios, scenarios.hard)
  # scenarios = scenarios[,c(-5, -6, -7, -8)]
  
  day.regret = function(vec){
    return(1 - coincidence(vec[2:4], vec[5:7]))
  }
  
  regrets = cbind(scenarios$V1, apply(scenarios, 1, day.regret)) %>% as.data.frame()
  names(regrets) = c("day", "regret")
  
  # mean.regret = c()
  # for(day in 1:nrow(regrets)){
  #       mean.regret = c(mean.regret, sum(regrets$regret[1:day] * c(1:day)) / sum(1:day)) # weighted average in relation to position in timeline
  # }
  # mean.regret = cbind(regrets$day, mean.regret %>% as.data.frame())
  # names(mean.regret) = c("day", "regret")
  
  # fwrite(mean.regret,
  #        paste0(address,"resultsentropy/hard.entropy.daily.regret.user", user, ".txt"),
  #        row.names = FALSE, col.names = FALSE, sep = "\t")

  fwrite(regrets,
         paste0(address,"resultsshiftband2/shiftband.daily.regret.nomean.user", user, ".txt"),
         row.names = FALSE, col.names = FALSE, sep = "\t")
   
}

pblapply(users, calculate.regrets)

```

```{r}

# test
# user = users[10]

# regret.line = regrets$ShiftBand
integrate.regrets = function(regret.line){
  day.range = ((1:(length(regret.line))) - 1) /  ((length(regret.line) - 1))
  integrate(approxfun(day.range , regret.line), 0, 1, subdivisions = 10000, stop.on.error = FALSE)$value
}

generate.line.areas = function(user){
  
  sb = fread(paste0(address, "resultsshiftband2/shiftband.daily.regret.nomean.user", user, ".txt"),
        sep = "\t", header = F)
  # reduce to 20% test
  test.days = ceiling(nrow(sb) / 5)
  sb = sb %>% slice((nrow(sb) - test.days + 1):nrow(sb))
  
  if(sb %>% nrow() > 1){

    etp = fread(paste0(address, "resultsentropy/entropy.daily.regret.nomean.user", user, ".txt"),
          sep = "\t", header = F)
    etp = etp %>% slice((nrow(sb) - test.days + 1):nrow(sb))
    
    ildpd = fread(paste0(address, "resultsildpd/ildpd.daily.regret.nomean.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd = ildpd %>% slice((nrow(sb) - test.days + 1):nrow(sb))
    
    regrets = cbind(sb, etp, ildpd)  
    regrets = regrets[,c(-1, -3, -5)]
    names(regrets) = c("ShiftBand", "Entropy", "ILDPD")
    
    apply(regrets, 2, integrate.regrets)
    
  }
}

regret.area = do.call(rbind, pbsapply(users, generate.line.areas))

fwrite(regret.area %>% as.data.frame(), 
       paste0(address, "resultsarea/regret.area.sb.entropy.ildpd.nomean.testset20pct.txt"),
       sep = "\t",
       row.names = F,
       col.names = T)

```


```{r}

# users available in 15 days recommendation

files <- list.files(path = paste0(address, "resultsildpd15days/"))

# test
# filename = files[1]

clean.user = function(filename){
  users = substring(filename, 36, nchar(filename) - 4)
}

users = clean.user(files)

# test
# user = users[1]

# regret.line = sb$V2
integrate.regrets = function(regret.line){
  day.range = ((1:(length(regret.line))) - 1) /  ((length(regret.line) - 1))
  integrate(approxfun(day.range , regret.line %>% as.list()), 0, 1, subdivisions = 10000, stop.on.error = FALSE)$value
}

generate.line.areas = function(user){
  
  sb = fread(paste0(address, "resultsshiftbandalpha01beta05gamma05/hard.shiftband.alpha01.beta05.gamma05.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
  sb.in = integrate.regrets(sb$V2)
  
  if(sb %>% nrow() > 16){
    
    ildpd = fread(paste0(address, "resultsildpd/hard.ildpd.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd.in = integrate.regrets(ildpd$V2)
    ildpd2 = fread(paste0(address, "resultsildpd/hard.ildpd.2days.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd2.in = integrate.regrets(ildpd2$V2)
    ildpd5 = fread(paste0(address, "resultsildpd/hard.ildpd.5days.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd5.in = integrate.regrets(ildpd5$V2)
    ildpd7 = fread(paste0(address, "resultsildpd/hard.ildpd.7days.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd7.in = integrate.regrets(ildpd7$V2)
    ildpd15 = fread(paste0(address, "resultsildpd/hard.ildpd.15days.daily.regret.user", user, ".txt"),
          sep = "\t", header = F)
    ildpd15.in = integrate.regrets(ildpd15$V2)
    
    regrets = c(sb.in, ildpd.in, ildpd2.in, ildpd5.in, ildpd7.in, ildpd15.in)
    
  }
}

regret.area = do.call(rbind, pbsapply(users, generate.line.areas))
regret.area = regret.area %>% as.data.frame()
names(regret.area) = c("ShiftBand", "ILDPD", "ILD-2", "ILD-5", "ILD-7", "ILD-15")

fwrite(regret.area %>% as.data.frame(), 
       paste0(address, "resultsarea/hard.regret.area.sb.ildpd.severaldays.txt"),
       sep = "\t",
       row.names = F,
       col.names = T)

```


```{r}

regret.area.melted = melt(regret.area %>% as.data.frame(), measure.vars = c(1:(regret.area %>% ncol())))
names(regret.area.melted) = c("method", "value")

g = ggplot(regret.area.melted, aes(x = method, y = value, fill = method)) +
  geom_boxplot() +
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g

ggsave(paste0(address, "resultsarea/plot.shiftband.entropy.ildpd.nomean.testset20pct.pdf"))
```

```{r}

# test
# user = users[1]

#users = users[1:10]

generate.user.graph.entropy.vs.shiftband = function(user){
  
  sb = fread(paste0(address, "resultsshiftbandalpha01beta05gamma05/shiftband.alpha01.beta05.gamma05.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
  
  sb01 = fread(paste0(address, "resultsshiftband2/shiftband.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
  
  #alpha = fread(paste0(address, "resultsshiftbandalpha/shiftband.daily.regret.user", user, ".txt"), sep = "\t", header = F)
  #beta = fread(paste0(address, "resultsshiftbandbeta/shiftband.daily.regret.user", user, ".txt"), sep = "\t", header = F)
  #gamma = fread(paste0(address, "resultsshiftbandgamma/shiftband.daily.regret.user", user, ".txt"), sep = "\t", header = F)
  
  etp = fread(paste0(address, "resultsentropy/entropy.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
  
  ildpd = fread(paste0(address, "resultsildpd/ildpd.daily.regret.user", user, ".txt"),
        sep = "\t", header = F)
  
  regrets = cbind(sb, etp, ildpd, sb01)  
  #regrets = cbind(sb, alpha, beta, gamma)  
  regrets = regrets[,c(-3, -5, -7)]
  names(regrets) = c("day", "ShiftBand", "Entropy", "ILDPD", "ShiftBand01")
  
  g <- ggplot(regrets, aes(day)) +
    geom_line(aes(y = ShiftBand, colour = "ShiftBand")) +
    geom_line(aes(y = Entropy, colour = "Entropy")) + 
    geom_line(aes(y = ILDPD, colour = "ILDPD")) +
    geom_line(aes(y = ShiftBand01, colour = "ShiftBand01"))
    
    #geom_line(aes(y = alpha, colour = "alpha")) +
    #geom_line(aes(y = beta, colour = "beta")) +
    #geom_line(aes(y = gamma, colour = "gamma"))
  ggsave(paste0(address, "plots_sb_etp_ildpd/graph.shiftband.vs.entropy.vs.ildpd.daily.regret.weighted.user", user,".pdf"))
  
}

pblapply(users, generate.user.graph.entropy.vs.shiftband)

```

