---
title: "R Notebook"
output: html_notebook
---



```{r}

if (!require("dplyr")) {
  install.packages("dplyr", repos="http://cran.rstudio.com/") 
}
if (!require("data.table")) {
  install.packages("data.table", repos="http://cran.rstudio.com/") 
}
if (!require("reshape")) {
  install.packages("reshape", repos="http://cran.rstudio.com/") 
}
if (!require("lsa")) {
  install.packages("lsa", repos="http://cran.rstudio.com/") 
}

library(dplyr)
library(data.table)
library(reshape)
library(lsa)
library(pbapply)

```

```{r}

########################## CONSTANTS ##########################

ALPHA = 0.1
BETA = 0.5
GAMMA = 0.5
ETA = 0.1
K = 8 # Number of scenarios
TRIALS = 10 
S = 5 # Number of days in user history

TOPN = 10
address <- "/local/Scripts/moad/"

```

```{r}

########################## DATA LOAD ############################

artist.data <- fread(paste0(address,"data/artist.data.txt"), 
                     sep = ";", 
                     verbose = TRUE,
                     header = TRUE)
artist.data = as.data.frame(artist.data)

# Correcting debut year from Rod Stewart - wrong in MusicBrainz

artist.data[which(artist.data$Artist == "The_Pains_of_Being_Pure_at_Heart"),"last"] = 2017
artist.data[which(artist.data$Artist == "Rod_Stewart"),"debut"] = 1968

# Input 0 in NA values

col = c(3:6)
for(i in col){
  artist.data[which(is.na(artist.data[,i])),i] = 0
}

data.train <- fread(paste0(address,"data/LFM_train.txt"), 
                    sep = "\t", 
                    verbose = TRUE,
                    header = TRUE)
data.train = as.data.frame(data.train)

data.test <- fread(paste0(address,"data/LFM_test.txt"), 
                   sep = "\t", 
                   verbose = TRUE,
                   header = TRUE)
data.test = as.data.frame(data.test)

```

```{r}
# Similarity and ILD functions

# real = real.scenario
# chosen = chosen.scenario

coincidence = function(real, chosen){
  if(length(chosen) == length(real)){
    sum.vec = chosen %>% as.numeric() + real %>% as.numeric()
    #sum.vec = ((sum.vec %% 2) - 1) %>% abs()
    sum.vec = (sum.vec == 1) %>% as.numeric()
    return((length(sum.vec) - sum(sum.vec)) / length(sum.vec))
  }
}

similarity.function.genre = function(data){
  return(cosine(t(as.matrix(data))))
}

similarity.function.locality = function(data){
  n = nrow(data)
  m = matrix(0L,n,n)
  N = nrow(artist.data)
  for(i in 1:n){
    for(j in 1:n){
      if(data[i,"area"] == data[j,"area"]){
        m[i,j] = 1
      } else {  
        m[i,j] = 1 / (1 + log10(N/(as.numeric(freq.area[which(data[i,"area"] == freq.area$area),"total"]))) 
                      * log10(N/(as.numeric(freq.area[which(data[j,"area"] == freq.area$area),"total"]))))
      }
    }
  }
  return(m)
}


similarity.function.contemporaneity = function(data){
  artistas = rownames(data)
  data$artista = artistas
  artist_simi = combn(artistas, 2) %>% t() %>% as_data_frame()
  
  sim_between_artists = function(x, data){
    a = x[1]
    b = x[2]
    a_data =  data %>% filter(artista %in% a)
    b_data =  data %>% filter(artista %in% b)
    
    pc = min(a_data$debut, b_data$debut)
    ut = max(a_data$last, b_data$last)
    
    uc = max(a_data$debut, b_data$debut)
    pt = min(a_data$last, b_data$last)
    
    if (ut == pc)
      return(1)
    
    sim = (pt - uc)/(ut - pc)
    return((sim+1)/2)
  }
  
  sim = apply(artist_simi, 1, sim_between_artists, data)
  artist_simi$sim = sim
  artist_simi_replicated = artist_simi %>% select(V1=V2, V2=V1, sim)
  artists_identity = data.frame(V1 = artistas, V2 = artistas, sim = 1)
  artist_simi = rbind(artist_simi, artist_simi_replicated, artists_identity)
  
  matrix = artist_simi %>% cast(V1~V2, mean, value = "sim") %>% select(-V1)
  
  matrix = matrix %>% as.matrix()
  return(matrix)
}

ILD = function(data, similarity.function){
  k=nrow(data)
  if(k > 1){
    sum.dissimilarity = 0
    similarity.matrix = similarity.function(data)
    dissimilarity.matrix = 1 - similarity.matrix
    sum.dissimilarity = sum(colSums(dissimilarity.matrix))
    return(sum.dissimilarity/(k*(k-1)))
  }else{
    return(0)
  }
}

list.ILD = function(list.elements){
  list.elements = list.elements %>% as.data.frame()
  size = nrow(list.elements)
  # list.elements = as.data.frame(artist.data[list.elements.index,"Artist"])
  names(list.elements) = "artist"
  # n = length(aspects.to.diversify)
  df = artist.data[artist.data$Artist %in% list.elements$artist,]
  
  return(c(
            ILD(df[(aspects[[1]])], similarity.function.contemporaneity),
            ILD(df[(aspects[[2]])], similarity.function.locality),
            ILD(df[(aspects[[3]])], similarity.function.genre))
          )
}

```

```{r}
########################################## ASPECTS ##########################################

aspects <- vector(mode="list", length=3)
names(aspects) <- c("Contemporaneity", "Locality", "Genre")
aspects[[1]] <- c(5,6); aspects[[2]] <- 4; aspects[[3]] <- 7:ncol(artist.data)
similarity.functions <- vector(mode="list", length=3)
names(similarity.functions) <- c("Contemporaneity", "Locality", "Genre")
similarity.functions[[1]] <- similarity.function.contemporaneity; similarity.functions[[2]] <- similarity.function.locality
similarity.functions[[3]] <- similarity.function.genre

#################### Calculate frequencies for IOF for type and Locality  ####################

by.area = group_by(artist.data,area)
freq.area = dplyr::summarise(by.area, total = n())

```

```{r}

# ShiftBand

  users = data.train$`user-id` %>% unique()

  # users = users[1:10] # sub-sample to test shiftband parameters

  all.ilds = fread(paste0(address,"results/daily.propensity.ILD.allusers.txt"), 
                   sep = ",") 
  
  # clean zeros and median
  names(all.ilds) = c("day", "contemporaneity", "locality", "genre")
  all.ilds.filtered = filter(all.ilds, contemporaneity > 0 & locality > 0 & genre > 0)
  
  summary.contemporaneity = summary(all.ilds.filtered$contemporaneity)
  summary.locality = summary(all.ilds.filtered$locality)
  summary.genre = summary(all.ilds.filtered$genre)
  
  #median.contemporaneity = median(all.ilds.filtered$contemporaneity)
  #median.locality = median(all.ilds.filtered$locality)
  #median.genre = median(all.ilds.filtered$genre)

  random.probability.sort = function(p){
    total = sum(p)
    target = runif(1, 0, total)
    i = 1
    while(total - p[i] > target){
      total = total - p[i]
      i = i + 1
    }
    return(i)
  }

  set.probability = function(i, w, W){
    return((1 - GAMMA) * w[i] / W + GAMMA / K)
  }
  
  set.weights = function(i, w, W, p, x.exp){
    return(w[i] * exp(ETA * (x.exp[i] + ALPHA / (p[i] * sqrt(TRIALS * K / S))))) # S = number of days)
  }
  
  ild.2.scenario = function(ilds) {
    x = 0.5; y = 0.5; z = 0.5
    if(ilds[1] >= summary.contemporaneity[5]) {x = 1}
    if(ilds[1] <= summary.contemporaneity[2]) {x = 0}
    if(ilds[2] >= summary.locality[5]) {y = 1}
    if(ilds[2] <= summary.locality[2]) {y = 0}
    if(ilds[3] >= summary.genre[5]) {z = 1}
    if(ilds[3] <= summary.genre[2]) {z = 0}
    return(c(x, y, z))
  }

  ild.2.scenario.no = function(ilds) {
    x = 0; y = 0; z = 0
    if(ilds[1] >= summary.contemporaneity[3]) {x = 1}
    if(ilds[2] >= summary.locality[3]) {y = 1}
    if(ilds[3] >= summary.genre[3]) {z = 1}
    return(c(x, y, z))
  }

 
# test
#user = 7687
#history = data.train

one.user.shiftband.ild = function(user, history){

  # setup ShiftBand
  w = rep(1,K)
  user.history = data.train[which(history$`user-id` == user),]
  user.history$timestamp = user.history$timestamp / (60*60*24) # timestamp in seconds switched to days
  user.history$timestamp = floor(user.history$timestamp)
  user.history.unique = user.history$timestamp %>% unique()
  S = length(user.history.unique)
  TRIALS = S

  # test
  #day = user.history.unique[1]
  
  df = data.frame()
  for (day in user.history.unique){
    # One day iter
    W = sum(w)
    p = lapply(c(1:K), set.probability, w, W) %>% as.numeric()
    
    it = random.probability.sort(p)
    
    chosen.scenario = c(FALSE,FALSE,FALSE)
    if(it >= 5){
      chosen.scenario[1] = TRUE
    }
    if(it == 3 | it == 4 | it == 7 | it == 8){
      chosen.scenario[2] = TRUE
    }
    if(it %% 2 == 0){
      chosen.scenario[3] = TRUE
    }
  
    day.history = user.history %>% filter(timestamp == day)
    ild.day = list.ILD(day.history$`artist-name`)
    #real.scenario = ild.2.scenario(ild.day)
    real.scenario = ild.2.scenario(ild.day)
    linha = c(day, chosen.scenario,real.scenario) %>% as.numeric() %>% as.data.frame() %>% t()
    df = rbind(df, linha)
    
    # collect reward
  
    xit = coincidence(real.scenario, chosen.scenario)
  
    x.exp = rep(0,K)
    x.exp[it] = xit / p[it]

    w = lapply(c(1:K), set.weights, w, W, p, x.exp) %>% as.numeric()
  
  } 
  fwrite(df,
           paste0(address,"resultsshiftbandalpha01beta05gamma05/shiftband.alpha01.beta05.gamma05.ild.daily.user",user,".txt"), 
           col.names = FALSE, row.names = FALSE, sep = ",")

}

pblapply(users, one.user.shiftband.ild, history = data.train)

```

```{r}

# join results in one file
nm <- list.files(path=paste0(address, "resultsshiftband"))

prov = lapply(nm, function(x) fread(input=paste0(address,"resultsshiftband/",x), sep = ",", header = FALSE)) 
all.results = do.call(rbind, prov)
fwrite(all.results,
        paste0(address,"resultsshiftband/shiftband.ild.daily.allusers.txt"), 
        col.names = FALSE, row.names = FALSE, quote = TRUE) 

```




